import "dotenv/config";
export const PORT = process.env.PORT;
export const CLIENT_ID = process.env.CLIENT_ID;
export const CLIENT_SECRET = process.env.CLIENT_SECRET;
export const CLIENT_URL = process.env.CLIENT_URL;
export const JWT_SECRET = process.env.JWT_SECRET;
export const JWT_EXPIRES = process.env.JWT_EXPIRES;
export const USER_EMAIL = process.env.USER_EMAIL;
export const EMAIL_PASS = process.env.EMAIL_PASS;
export const BASE_URL_CLIENT = process.env.BASE_URL_CLIENT;